### ISSUE TITLE
"No summary" in live demo looks funny

### ISSUE THREAD

**Issue by vkvelho** [chemerisuk/better-details-polyfill#1]
Hi! This issue is likely to be false positive, but anyways... I had a quick look at the live demo and noticed the "No summary" example doesn't look right. I really don't know if this polyfill has anything to do with the issue though.

![chrome 39](https://cloud.githubusercontent.com/assets/1226045/5235797/07696316-781c-11e4-9969-4f81c723dce2.png)
![safari 8](https://cloud.githubusercontent.com/assets/1226045/5235798/07a0261c-781c-11e4-8d1c-a29b3c23c250.png)

**Comment by chemerisuk** [comment]
Hi @vkvelho, you are right, current styles have some issue in WebKit browsers in "No summary" scenario. I hope to find a way to get rid of native styling completely, but it's more tricky than I expected. So for now I decided to keep it as it is, because the use case is rare.

**Comment by chemerisuk** [comment]
Found [fix](https://github.com/chemerisuk/better-details-polyfill/blob/master/src/main.css#L64) for Chrome, and Safari is almost good too.

**Comment by chemerisuk** [comment]
In version 2.1.0 markup for edge cases will be consistent in ALL browsers: with or without native support. So all those display issues will be fixed.

**Comment by chemerisuk** [comment]
fixed in version 2.1.0
